version: '3.8'

services:
  spotify-downloader:
    build: .
    container_name: spotify-downloader
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - YOUTUBE_API_KEY_1=${YOUTUBE_API_KEY_1}
      - YOUTUBE_API_KEY_2=${YOUTUBE_API_KEY_2}
      - YOUTUBE_API_KEY_3=${YOUTUBE_API_KEY_3}
      - YOUTUBE_API_KEY_4=${YOUTUBE_API_KEY_4}
      - YOUTUBE_API_KEY_5=${YOUTUBE_API_KEY_5}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    restart: unless-stopped
